/**
 * Supported spoken languages for Gemini 3.5 Transcribe model (85+ languages and dialects).
 * Each entry has:
 *  - code: BCP-47 locale or ISO tag accepted by Gemini 3.5 Transcribe
 *  - name: English language name
 *  - nativeName: Native language name in its native script
 *  - label: Formatted label for dropdown display
 */

export const POPULAR_TRANSCRIBE_LANGUAGES = [
    { code: 'be-BY', name: 'Belarusian', nativeName: 'Беларуская', label: 'Беларуская (Belarusian)' },
    { code: 'en-US', name: 'English (US)', nativeName: 'English (US)', label: 'English (US)' },
    { code: 'ru-RU', name: 'Russian', nativeName: 'Русский', label: 'Русский (Russian)' },
    { code: 'uk-UA', name: 'Ukrainian', nativeName: 'Українська', label: 'Українська (Ukrainian)' },
    { code: 'pl-PL', name: 'Polish', nativeName: 'Polski', label: 'Polski (Polish)' },
    { code: 'es-ES', name: 'Spanish', nativeName: 'Español', label: 'Español (Spanish)' },
    { code: 'de-DE', name: 'German', nativeName: 'Deutsch', label: 'Deutsch (German)' },
    { code: 'fr-FR', name: 'French', nativeName: 'Français', label: 'Français (French)' },
    { code: 'it-IT', name: 'Italian', nativeName: 'Italiano', label: 'Italiano (Italian)' },
    { code: 'pt-BR', name: 'Portuguese (Brazil)', nativeName: 'Português (Brasil)', label: 'Português (Brasil)' },
    { code: 'zh-CN', name: 'Chinese (Simplified)', nativeName: '中文 (简体)', label: '中文 (Chinese Simplified)' },
    { code: 'ja-JP', name: 'Japanese', nativeName: '日本語', label: '日本語 (Japanese)' },
    { code: 'ko-KR', name: 'Korean', nativeName: '한국어', label: '한국어 (Korean)' },
]

export const ALL_TRANSCRIBE_LANGUAGES = [
    { code: 'af-ZA', name: 'Afrikaans', nativeName: 'Afrikaans', label: 'Afrikaans' },
    { code: 'sq-AL', name: 'Albanian', nativeName: 'Shqip', label: 'Shqip (Albanian)' },
    { code: 'am-ET', name: 'Amharic', nativeName: 'አማርኛ', label: 'አማርኛ (Amharic)' },
    { code: 'ar-EG', name: 'Arabic (Egypt)', nativeName: 'العربية (مصر)', label: 'العربية (Arabic - Egypt)' },
    { code: 'ar-SA', name: 'Arabic (Saudi Arabia)', nativeName: 'العربية (السعودية)', label: 'العربية (Arabic - Saudi Arabia)' },
    { code: 'ar-AE', name: 'Arabic (UAE)', nativeName: 'العربية (الإمارات)', label: 'العربية (Arabic - UAE)' },
    { code: 'hy-AM', name: 'Armenian', nativeName: 'Հայերեն', label: 'Հայերեն (Armenian)' },
    { code: 'az-AZ', name: 'Azerbaijani', nativeName: 'Azərbaycan', label: 'Azərbaycan (Azerbaijani)' },
    { code: 'eu-ES', name: 'Basque', nativeName: 'Euskara', label: 'Euskara (Basque)' },
    { code: 'be-BY', name: 'Belarusian', nativeName: 'Беларуская', label: 'Беларуская (Belarusian)' },
    { code: 'bn-BD', name: 'Bengali (Bangladesh)', nativeName: 'বাংলা (বাংলাদেশ)', label: 'বাংলা (Bengali - Bangladesh)' },
    { code: 'bn-IN', name: 'Bengali (India)', nativeName: 'বাংলা (ভারত)', label: 'বাংলা (Bengali - India)' },
    { code: 'bs-BA', name: 'Bosnian', nativeName: 'Bosanski', label: 'Bosanski (Bosnian)' },
    { code: 'bg-BG', name: 'Bulgarian', nativeName: 'Български', label: 'Български (Bulgarian)' },
    { code: 'my-MM', name: 'Burmese', nativeName: 'မြန်မာ', label: 'မြန်မာ (Burmese)' },
    { code: 'ca-ES', name: 'Catalan', nativeName: 'Català', label: 'Català (Catalan)' },
    { code: 'ceb-PH', name: 'Cebuano', nativeName: 'Cebuano', label: 'Cebuano' },
    { code: 'yue-Hant-HK', name: 'Chinese (Cantonese)', nativeName: '粵語', label: '粵語 (Cantonese)' },
    { code: 'zh-CN', name: 'Chinese (Simplified)', nativeName: '简体中文', label: '简体中文 (Chinese Simplified)' },
    { code: 'zh-TW', name: 'Chinese (Traditional)', nativeName: '繁體中文', label: '繁體中文 (Chinese Traditional)' },
    { code: 'hr-HR', name: 'Croatian', nativeName: 'Hrvatski', label: 'Hrvatski (Croatian)' },
    { code: 'cs-CZ', name: 'Czech', nativeName: 'Čeština', label: 'Čeština (Czech)' },
    { code: 'da-DK', name: 'Danish', nativeName: 'Dansk', label: 'Dansk (Danish)' },
    { code: 'nl-BE', name: 'Dutch (Belgium)', nativeName: 'Nederlands (België)', label: 'Nederlands (Dutch - Belgium)' },
    { code: 'nl-NL', name: 'Dutch (Netherlands)', nativeName: 'Nederlands (Nederland)', label: 'Nederlands (Dutch)' },
    { code: 'en-AU', name: 'English (Australia)', nativeName: 'English (Australia)', label: 'English (Australia)' },
    { code: 'en-GB', name: 'English (UK)', nativeName: 'English (UK)', label: 'English (UK)' },
    { code: 'en-IN', name: 'English (India)', nativeName: 'English (India)', label: 'English (India)' },
    { code: 'en-US', name: 'English (US)', nativeName: 'English (US)', label: 'English (US)' },
    { code: 'et-EE', name: 'Estonian', nativeName: 'Eesti', label: 'Eesti (Estonian)' },
    { code: 'fil-PH', name: 'Filipino (Tagalog)', nativeName: 'Filipino', label: 'Filipino / Tagalog' },
    { code: 'fi-FI', name: 'Finnish', nativeName: 'Suomi', label: 'Suomi (Finnish)' },
    { code: 'fr-CA', name: 'French (Canada)', nativeName: 'Français (Canada)', label: 'Français (French - Canada)' },
    { code: 'fr-FR', name: 'French (France)', nativeName: 'Français (France)', label: 'Français (French)' },
    { code: 'gl-ES', name: 'Galician', nativeName: 'Galego', label: 'Galego (Galician)' },
    { code: 'ka-GE', name: 'Georgian', nativeName: 'ქართული', label: 'ქართული (Georgian)' },
    { code: 'de-AT', name: 'German (Austria)', nativeName: 'Deutsch (Österreich)', label: 'Deutsch (German - Austria)' },
    { code: 'de-DE', name: 'German (Germany)', nativeName: 'Deutsch (Deutschland)', label: 'Deutsch (German)' },
    { code: 'de-CH', name: 'German (Switzerland)', nativeName: 'Deutsch (Schweiz)', label: 'Deutsch (German - Switzerland)' },
    { code: 'el-GR', name: 'Greek', nativeName: 'Ελληνικά', label: 'Ελληνικά (Greek)' },
    { code: 'gu-IN', name: 'Gujarati', nativeName: 'ગુજરાતી', label: 'ગુજરાતી (Gujarati)' },
    { code: 'ha-NG', name: 'Hausa', nativeName: 'Harshen Hausa', label: 'Hausa' },
    { code: 'he-IL', name: 'Hebrew', nativeName: 'עברית', label: 'עברית (Hebrew)' },
    { code: 'hi-IN', name: 'Hindi', nativeName: 'हिन्दी', label: 'हिन्दी (Hindi)' },
    { code: 'hu-HU', name: 'Hungarian', nativeName: 'Magyar', label: 'Magyar (Hungarian)' },
    { code: 'is-IS', name: 'Icelandic', nativeName: 'Íslenska', label: 'Íslenska (Icelandic)' },
    { code: 'id-ID', name: 'Indonesian', nativeName: 'Bahasa Indonesia', label: 'Bahasa Indonesia (Indonesian)' },
    { code: 'ga-IE', name: 'Irish', nativeName: 'Gaeilge', label: 'Gaeilge (Irish)' },
    { code: 'it-IT', name: 'Italian', nativeName: 'Italiano', label: 'Italiano (Italian)' },
    { code: 'ja-JP', name: 'Japanese', nativeName: '日本語', label: '日本語 (Japanese)' },
    { code: 'jv-ID', name: 'Javanese', nativeName: 'Basa Jawa', label: 'Basa Jawa (Javanese)' },
    { code: 'kn-IN', name: 'Kannada', nativeName: 'ಕನ್ನಡ', label: 'ಕನ್ನಡ (Kannada)' },
    { code: 'kk-KZ', name: 'Kazakh', nativeName: 'Қазақша', label: 'Қазақша (Kazakh)' },
    { code: 'km-KH', name: 'Khmer', nativeName: 'ភាសាខ្មែរ', label: 'ភាសាខ្មែរ (Khmer)' },
    { code: 'ko-KR', name: 'Korean', nativeName: '한국어', label: '한국어 (Korean)' },
    { code: 'lo-LA', name: 'Lao', nativeName: 'ພາສາລາວ', label: 'ພາສາລາວ (Lao)' },
    { code: 'la', name: 'Latin', nativeName: 'Latina', label: 'Latina (Latin)' },
    { code: 'lv-LV', name: 'Latvian', nativeName: 'Latviešu', label: 'Latviešu (Latvian)' },
    { code: 'lt-LT', name: 'Lithuanian', nativeName: 'Lietuvių', label: 'Lietuvių (Lithuanian)' },
    { code: 'mk-MK', name: 'Macedonian', nativeName: 'Македонски', label: 'Македонски (Macedonian)' },
    { code: 'ms-MY', name: 'Malay', nativeName: 'Bahasa Melayu', label: 'Bahasa Melayu (Malay)' },
    { code: 'ml-IN', name: 'Malayalam', nativeName: 'മലയാളം', label: 'മലയാളം (Malayalam)' },
    { code: 'mt-MT', name: 'Maltese', nativeName: 'Malti', label: 'Malti (Maltese)' },
    { code: 'mr-IN', name: 'Marathi', nativeName: 'मराठी', label: 'मराठी (Marathi)' },
    { code: 'mn-MN', name: 'Mongolian', nativeName: 'Монгол', label: 'Монгол (Mongolian)' },
    { code: 'ne-NP', name: 'Nepali', nativeName: 'नेपाली', label: 'नेपाली (Nepali)' },
    { code: 'no-NO', name: 'Norwegian', nativeName: 'Norsk', label: 'Norsk (Norwegian)' },
    { code: 'ps-AF', name: 'Pashto', nativeName: 'پښتو', label: 'پښتو (Pashto)' },
    { code: 'fa-IR', name: 'Persian', nativeName: 'فارسی', label: 'فارسی (Persian)' },
    { code: 'pl-PL', name: 'Polish', nativeName: 'Polski', label: 'Polski (Polish)' },
    { code: 'pt-BR', name: 'Portuguese (Brazil)', nativeName: 'Português (Brasil)', label: 'Português (Brasil)' },
    { code: 'pt-PT', name: 'Portuguese (Portugal)', nativeName: 'Português (Portugal)', label: 'Português (Portugal)' },
    { code: 'pa-IN', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ', label: 'ਪੰਜਾਬੀ (Punjabi)' },
    { code: 'ro-RO', name: 'Romanian', nativeName: 'Română', label: 'Română (Romanian)' },
    { code: 'ru-RU', name: 'Russian', nativeName: 'Русский', label: 'Русский (Russian)' },
    { code: 'sr-RS', name: 'Serbian', nativeName: 'Српски', label: 'Српски (Serbian)' },
    { code: 'si-LK', name: 'Sinhala', nativeName: 'සිංහල', label: 'සිංහල (Sinhala)' },
    { code: 'sk-SK', name: 'Slovak', nativeName: 'Slovenčina', label: 'Slovenčina (Slovak)' },
    { code: 'sl-SI', name: 'Slovenian', nativeName: 'Slovenščina', label: 'Slovenščina (Slovenian)' },
    { code: 'so-SO', name: 'Somali', nativeName: 'Soomaali', label: 'Soomaali (Somali)' },
    { code: 'es-419', name: 'Spanish (Latin America)', nativeName: 'Español (Latinoamérica)', label: 'Español (Latin America)' },
    { code: 'es-ES', name: 'Spanish (Spain)', nativeName: 'Español (España)', label: 'Español (Spain)' },
    { code: 'es-US', name: 'Spanish (US)', nativeName: 'Español (EE. UU.)', label: 'Español (US)' },
    { code: 'su-ID', name: 'Sundanese', nativeName: 'Basa Sunda', label: 'Basa Sunda (Sundanese)' },
    { code: 'sw-KE', name: 'Swahili', nativeName: 'Kiswahili', label: 'Kiswahili (Swahili)' },
    { code: 'sv-SE', name: 'Swedish', nativeName: 'Svenska', label: 'Svenska (Swedish)' },
    { code: 'ta-IN', name: 'Tamil', nativeName: 'தமிழ்', label: 'தமிழ் (Tamil)' },
    { code: 'te-IN', name: 'Telugu', nativeName: 'తెలుగు', label: 'తెలుగు (Telugu)' },
    { code: 'th-TH', name: 'Thai', nativeName: 'ไทย', label: 'ไทย (Thai)' },
    { code: 'tr-TR', name: 'Turkish', nativeName: 'Türkçe', label: 'Türkçe (Turkish)' },
    { code: 'uk-UA', name: 'Ukrainian', nativeName: 'Українська', label: 'Українська (Ukrainian)' },
    { code: 'ur-PK', name: 'Urdu', nativeName: 'اردو', label: 'اردو (Urdu)' },
    { code: 'uz-UZ', name: 'Uzbek', nativeName: 'Oʻzbekcha', label: 'Oʻzbekcha (Uzbek)' },
    { code: 'vi-VN', name: 'Vietnamese', nativeName: 'Tiếng Việt', label: 'Tiếng Việt (Vietnamese)' },
    { code: 'cy-GB', name: 'Welsh', nativeName: 'Cymraeg', label: 'Cymraeg (Welsh)' },
    { code: 'yi', name: 'Yiddish', nativeName: 'ייִדיש', label: 'ייִדיש (Yiddish)' },
    { code: 'yo-NG', name: 'Yoruba', nativeName: 'Yorùbá', label: 'Yorùbá (Yoruba)' },
    { code: 'zu-ZA', name: 'Zulu', nativeName: 'isiZulu', label: 'isiZulu (Zulu)' },
]
